"""Typed run data; no collection, execution, or storage takes place here.

Use dataclasses.asdict(record) to obtain a JSON-compatible dictionary. Timestamps
are UTC strings supplied by the caller; durations are seconds and memory is bytes.
None means unknown or unavailable, not zero. Collection warnings explain missing
environment fields, while Git and CUDA metrics carry their own missing reasons.
"""

from dataclasses import dataclass, field
from typing import Literal

RunStatus = Literal["running", "succeeded", "failed"]


@dataclass
class GPUInfo:
    """A visible GPU's process-local device identifier and available name."""

    device: str
    name: str | None = None


@dataclass
class EnvironmentInfo:
    """Observed environment; None is unknown, while an empty GPU list means none."""

    python_version: str | None = None
    os: str | None = None
    architecture: str | None = None
    pytorch_version: str | None = None
    cuda_build_version: str | None = None
    cuda_available: bool | None = None
    gpus: list[GPUInfo] | None = None


@dataclass
class GitInfo:
    """Pre-run Git state; dirty=False means clean, dirty=None means unknown."""

    commit: str | None = None
    dirty: bool | None = None
    unavailable_reason: str | None = None


@dataclass
class CUDADeviceMetrics:
    """Allocator peaks for one device; explain which peaks are missing and why."""

    device: str
    peak_allocated_bytes: int | None
    peak_reserved_bytes: int | None
    unavailable_reason: str | None = None

    def __post_init__(self) -> None:
        peaks = (self.peak_allocated_bytes, self.peak_reserved_bytes)
        if any(value is not None and value < 0 for value in peaks):
            raise ValueError("CUDA peaks must be non-negative.")
        if None in peaks and not self.unavailable_reason:
            raise ValueError("Missing CUDA peaks require an unavailable_reason.")
        if None not in peaks and self.unavailable_reason is not None:
            raise ValueError("Available CUDA peaks cannot have an unavailable_reason.")


@dataclass
class RunMetrics:
    """Per-device peaks, or an overall reason when no CUDA metrics are available.

    measurement_scope describes the interval covered by the peaks, when known.
    Device entries retain context only; this model does not pair or aggregate GPUs.
    """

    cuda_devices: list[CUDADeviceMetrics]
    measurement_scope: str | None = None
    unavailable_reason: str | None = None

    def __post_init__(self) -> None:
        if not self.cuda_devices and not self.unavailable_reason:
            raise ValueError("Missing CUDA metrics require an unavailable_reason.")
        if self.cuda_devices and self.unavailable_reason is not None:
            raise ValueError(
                "CUDA device metrics cannot have an overall unavailable_reason."
            )


@dataclass
class RunDiagnostics:
    """Training failure details are independent of optional collection warnings."""

    failure_message: str | None = None
    collection_warnings: list[str] = field(default_factory=list)


@dataclass
class RunRecord:
    """One run, using schema version 1 independently of the TrainLens version.

    Identity and command data are supplied, never generated by this model.
    running means completion is not yet confirmed; succeeded and failed record
    the training outcome. Status is supplied independently of metric availability.
    Missing times, runtime, or exit code remain None until known. Callers supply
    consistent outcomes; this data class does not implement lifecycle transitions.
    """

    run_id: str
    name: str
    trainlens_version: str
    command: list[str]
    cwd: str
    schema_version: int = field(default=1, init=False)
    python_executable: str | None = None
    started_at: str | None = None
    ended_at: str | None = None
    runtime_seconds: float | None = None
    status: RunStatus = "running"
    exit_code: int | None = None
    environment: EnvironmentInfo = field(default_factory=EnvironmentInfo)
    git: GitInfo = field(
        default_factory=lambda: GitInfo(unavailable_reason="not_collected")
    )
    metrics: RunMetrics = field(
        default_factory=lambda: RunMetrics(
            cuda_devices=[], unavailable_reason="not_collected"
        )
    )
    diagnostics: RunDiagnostics = field(default_factory=RunDiagnostics)

    def __post_init__(self) -> None:
        if self.status not in ("running", "succeeded", "failed"):
            raise ValueError("Run status must be running, succeeded, or failed.")
